### ISSUE TITLE
While doing HTTP request from a browser getting following error error: { Error: tunneling socket could not be established, statusCode=403} Splunk SDK

### ISSUE THREAD

**Issue by priyanka-ukirde** [splunk/splunk-sdk-javascript#102]
```
var service = new splunkjs.Service({
        username: SPLUNK_USERNAME,
        password: SPLUNK_PASSWORD,
        scheme: SCHEME,
        host: HOST,
        port: PORT
 });

 service.login(function (err, success) {})
```
When code execution goes to service.loging it gives an error

` { Error: tunneling socket could not be established, statusCode=403}`
on the server where my code is deployed, I have written a script to test the above part of code on the server it is working fine on the server. Facing this issue while doing a HTTP request from the browser.

**Comment by shakeelmohamed** [comment]
Hi @priyanka-ukirde,

Which port are you using? The SDK uses the management port, which is 8089 by default in Splunk Enterprise.
Additionally, if your Splunk Enterprise instance is behind a load balancer or proxy there may be some additional configuration needed.
Feel free to reach out to us devinfo@splunk.com if you need further guidance, especially if you don't want to share details publicly.

**Comment by ncanumalla-splunk** [comment]
@priyanka-ukirde Please let us know if you are still experiencing this issue. Can you also please provide more information about SDK version you are using, the Splunk environment version, steps to reproduce and any other information?

**Comment by ncanumalla-splunk** [comment]
Closing this issue due to lack of response. Please reopen if this issue occurs again.
