### ISSUE TITLE
Auth token usage from develop branch production ready? When is it gonna be released?

### ISSUE THREAD

**Issue by BGrasnick** [splunk/splunk-sdk-javascript#144]
Hey,

I see that in your develop branch you already have integrated authentication via auth token. This is a feature we really need so we are wondering if this is already production ready and when a new release will be happening? 

Thanks already!

**Comment by ashah-splunk** [comment]
Hi @BGrasnick , we have released a new JS SDK version 1.11.0 few weeks back.
