### ISSUE TITLE
Github modinput example fails when target repo has fewer than 100 commits

### ISSUE THREAD

**Issue by splnkit** [splunk/splunk-sdk-javascript#35]
Small bug. res.meta object does not have a "link" attribute if fewer than 100 commits in target repo

    /opt/splunk/etc/apps/github_commits/bin/app/github_commits.js:170
                         if (res.meta.link.indexOf("rel=\"next\"") < 0) {
                                         ^
     TypeError: Cannot call method 'indexOf' of undefined
         at exports.streamEvents (/opt/splunk/etc/apps/github_commits/bin/app/github_commits.js:170:43)
         at getCommits (/opt/splunk/etc/apps/github_commits/bin/app/node_modules/github/api/v3.0.0/repos.js:898:17)

**Fix:** Add simple  !res.meta.hasOwnProperty("link")  check to the if clause

**Comment by shakeelmohamed** [comment]
Hi @splnkit thanks for this! We'll be sure to address it with the next release

**Comment by glennblock** [comment]
Thanks @splnkit!
