### ISSUE TITLE
node_modules in the repository

### ISSUE THREAD

**Issue by tusbar** [splunk/splunk-sdk-javascript#37]
Dependencies are already listed in `package.json`, there’s no need to have them in the repository.

Is there any specific reason?

**Comment by itay** [comment]
It allows folks who just download a zip of the repository or clone it via Git to not need to run `npm install` just to get all the dependencies, simplifying the installation process (as it removes a step). It also makes it easier to include in larger packages, as it will not need internet access in the future.

For folks who who wants to re-run `npm install` to get the latest, they can still do that.

**Comment by glennblock** [comment]
Thanks @tusbar. We'll discuss this.

**Comment by tusbar** [comment]
@itay people have internet access nowadays :)

https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git

**Comment by itay** [comment]
@tusbar that's not quite true. For example, internally, we build our packages in a chroot-ed environment that does not have external network access. This is not an uncommon pattern. Additionally, by ensuring that the package dependencies are all local, we can ensure bit-for-bit dependencies.

As @glennblock noted, we're looking into this, but it's not a simple question one way or the other. There are pros and cons either way.

**Comment by shakeelmohamed** [comment]
I'd like to chime in here and say there's not much of a downside to keeping them checked in. However, if we suddenly remove them from the repo that could make life harder for users who're already used to them being included. For the sake of consistency, I'd like to continue keeping them checked in.

**Comment by itay** [comment]
For now, we're going to keep it as is.
