### ISSUE TITLE
HighCharts SplineSerie integration missing

### ISSUE THREAD

**Issue by NicolasYDDER** [splunk/splunk-sdk-javascript#40]
Hi folks,

I'm trying to use the integrated HighCharts version (3.0.10)  in Splunk to implement a SplineSerie on my splunk app.
It seems this Object isn't available throught HighChart version implemented in Splunk....Why ?
Someone could proprose to me a workaround to use it ?

BR

Nicolas.

**Comment by itay** [comment]
@NicolasYDDER the version of highcharts that is bundled with the SDK is as of Splunk 5, and is at version 2.1.7. If you want to use the latest and greatest from a UI standpoint, I would highly recommend using the Web Framework: http://dev.splunk.com/webframework
