### ISSUE TITLE
Make a client-side code AMD and CommonJS compliant

### ISSUE THREAD

**Issue by bricss** [splunk/splunk-sdk-javascript#41]
Please, make a client-side code AMD and CommonJS compliant for use with RequireJS and Browserify as well and don't export `splunkjs` in global (window) if it used within module loaders.

**Comment by bricss** [comment]
https://github.com/umdjs/umd

**Comment by itay** [comment]
@bricss we do not have intentions to do so at the moment, given that the vast majority of usage we have right now is server-side, and it would be a large amount of work to update how we build the JS files.

If you want to contribute a Pull Request to do so, we would be more happy to evaluate it and work to get it merged. I'll close the issue until then.
