### ISSUE TITLE
Delete node_modules directory?

### ISSUE THREAD

**Issue by EcutDavid** [splunk/splunk-sdk-javascript#49]
1. People can install these modules by simply running `npm install`.
2. This repo will become unnecessary big when we upgrade these third party modules.

Thanks!

**Comment by shakeelmohamed** [comment]
Hi @EcutDavid,

Please see #37 for our rationale on leaving `node_modules` checked in.

**Comment by EcutDavid** [comment]
Thank you @shakeelmohamed
