### ISSUE TITLE
update used version of minified $script

### ISSUE THREAD

**Issue by poet-of-the-fall** [splunk/splunk-sdk-javascript#50]
Hi,

I use the SDK together with Angular 2. Painting one chart was no problem, but as I wanted to paint a second one, it didn't work. I traced it down to the "UI.loadCharting" function. The passed callback is only called, if $script loads the file from the server. If using the function for creating a second chart, the callback will not be executed (as the file is already loaded).
I fixed it by replacing the included minified version of $script by the current one.

**Comment by EcutDavid** [comment]
You mean `<script type="text/javascript" src="/yourpath/splunk.js"></script>` works but not for `<script type="text/javascript" src="/yourpath/splunk.js"></script>`?

**Comment by tdhellmann** [comment]
Hi @poet-of-the-fall - to clarify, you're talking about our use of [$script.js](https://github.com/ded/script.js/), right? 

We're open to pull requests - especially if you've got the patch done already.

**Comment by poet-of-the-fall** [comment]
Hi @tdhellmann, yes, I'm talking about $script.js.

I did fix it locally within the file I needed and did not use the whole repository.
Now I just checked out the repo and tried to fix it the right way (replacing $script.js with the current verison and compiling), but I was not able to run the "sdkdo compile" command, as browserify throwed some error.

**Comment by shakeelmohamed** [comment]
@poet-of-the-fall which version of node are you using? Running `sdkdo compile` requires v0.10 or v0.12

**Comment by poet-of-the-fall** [comment]
Thanks @tdhellmann, I missed that.
Pull request is opened.
