### ISSUE TITLE
Did the release tags change?

### ISSUE THREAD

**Issue by larsxschneider** [splunk/splunk-sdk-javascript#55]
Hi,

the release 1.8.2 tag of my fork points to https://github.com/splunk/splunk-sdk-javascript/commit/be284d2265afce1a31972f850ebc55bb3cde9f07 (orphaned, but also in your repo).

However, your release 1.8.2 tag points to https://github.com/splunk/splunk-sdk-javascript/commit/0f37a9c120cfb976d5caf80986a1a0a42e5f71f3

Did you change your release tags?

Thanks,
Lars

**Comment by shakeelmohamed** [comment]
Hi @larsxschneider,

We haven't changed anything, not sure how this happened but I don't think there's anything actionable for us here. Please re-open if I'm mistaken.
