### ISSUE TITLE
EProto 600 error when using node 9

### ISSUE THREAD

**Issue by jrgleason** [splunk/splunk-sdk-javascript#56]
I am trying to connect using node 9. When I do so I get...

    Error: {"response":{"headers":{},"statusCode":600},"status":600,"error":{"errno":"EPROTO","code":"EPROTO","syscall":"write"}}

It looks like this might be due to [this](https://github.com/nodejs/node/issues/3692) 

> I had

    var headers = {
      ...
      'Content-Type': 'text/xml',
      'Content-Length': Buffer(body).byteLength
    };

>But I think this was the culpritL

    var headers = {
      ...
      'Content-Type': 'text/xml',
      'Content-Length': body.length
    };

I see the [same code](https://github.com/splunk/splunk-sdk-javascript/blob/2afaa209594795af0e5882a9b0d4e8666207a492/lib/platform/node/node_http.js) in the project...

`request_options.headers["Content-Length"] = Buffer.byteLength(request_options.body, "utf8");`

**Comment by shakeelmohamed** [comment]
We've filed this internally as DVPL-7283, and will take a look

**Comment by shakeelmohamed** [comment]
We've merged #65 into the develop branch. It will be out in the next release
