### ISSUE TITLE
examples attempt to authorize against non-existent endpoint

### ISSUE THREAD

**Issue by cdaringe** [splunk/splunk-sdk-javascript#60]
# problem

- examples attempt to auth against an endpoint that returns a `404`
  - e.g. `http://<ip>/services/auth/login?output_mode=json`

# discussion

-  my splunk dev server,`http://<ip>` is a thing, and redirects to `http://<ip>/en-US/app/launcher/home`
    - `http://<ip>/services/` 404s.
    - splunk enterprise `7.0.2`

thanks!

**Comment by cdaringe** [comment]
it looks like the ui login `POST`s to `/en-US/account/login`, if its worth anything.

**Comment by shakeelmohamed** [comment]
Hi @cdaringe, which port are you connecting to? The SDKs need to connect to the management port (8089 by default) instead of the web port (8000 by default)

**Comment by cdaringe** [comment]
ah, i see.  thx.  bummer, now `request` is emitting `ECONNRESET`s w/out much context, from w/in the proxy server
