### ISSUE TITLE
Security vulnerabilities 

### ISSUE THREAD

**Issue by dmali2** [splunk/splunk-sdk-javascript#64]
<img width="478" alt="screen shot 2018-05-24 at 11 57 33 am" src="https://user-images.githubusercontent.com/33879753/40505643-beafb74c-5f49-11e8-9e18-33a1b969027c.png">
<img width="477" alt="screen shot 2018-05-24 at 12 02 46 pm" src="https://user-images.githubusercontent.com/33879753/40505851-684a7f12-5f4a-11e8-9ea4-492e5702aad8.png">
<img width="479" alt="screen shot 2018-05-24 at 11 57 50 am" src="https://user-images.githubusercontent.com/33879753/40505644-bec5386a-5f49-11e8-8530-95a9aa48a11b.png">

**Comment by shakeelmohamed** [comment]
We've already merged an upgrade of request which takes care of the `tough-cookie` vulnerability, the rest of these aren't high priority.

**Comment by dmali2** [comment]
I see the PR 63 was closed recently, when can we expect 1.8.4 npm version

**Comment by shakeelmohamed** [comment]
@tdhellmann any idea?

**Comment by dmali2** [comment]
@tdhellmann any update on the new node version?

**Comment by dmali2** [comment]
Are we expecting the new version anytime soon?
