### ISSUE TITLE
axios call to localhost splunk 404

### ISSUE THREAD

**Issue by hgrbble1** [splunk/splunk-sdk-javascript#66]
Hi I am using react.js and was wanting to use axios to make http request to the splunk rest api. I can curl my own local splunk with 
`curl  -k https://localhost:8089/services/auth/login --data-urlencode
username=admin --data-urlencode password=password`
But when I try to do

`axios.post({
      url: 'https://localhost:8089/services/auth/login',
      data: {
        username: 'username',
        password: 'password'
      }
    })

        .then((response) => {
           console.log(response);
         })
         .catch((error) => {
           console.log(error);
           if (error.response) {
             console.log(error.response.data);
             console.log(error.response.status);
             console.log(error.response.headers);

           }
           else if (error.request) {
             console.log(error.request);
           }
           else {
             console.log('Error', error.message);
           }
           console.log(error.config);
         })`
I get a 404 error.
I am using free splunk when I am trying to connect.
Is the 404 error because of something to do with CORS?
I am also interested in maybe using the splunk javascript sdk but when I read about the related issue(https://github.com/splunk/splunk-sdk-javascript/issues/61) I have no idea where to start and how to use browserify.
Any help is much appreciated thanks!

**Comment by shakeelmohamed** [comment]
Hi @hgrbble1, you should use the `auth` property instead of `data` to use basic auth with axios.

The 404 seems a bit odd, but is most likely related to CORS.

Click the link in my comment on #61, I have a short example of how to run browserify.

**Comment by hgrbble1** [comment]
I can get a response back from the https call in postman when I turn off ssl. When ssl is turned on I can not get access to it. I am using free splunk on my laptop.

**Comment by shakeelmohamed** [comment]
This issue doesn't seem related to the SDK according to you previous comment, please re-open if you find that the issue is related to the SDK specifically.
