### ISSUE TITLE
Secure username and password.

### ISSUE THREAD

**Issue by saibimajdi** [splunk/splunk-sdk-javascript#71]
Hello,

I'm trying to create an HTML page that connects to Splunk Enterprise and execute a search query. This page will be accessible publically for end users.
Hince, I'm looking for a way to secure my Splunk credentials. I there a way to that? Like API Key or encrypted credentials.

Is there another way instead of this one?

`svc = new splunkjs.Service(http, { 
                scheme: 'http',
                host: 'localhost',
                username: 'admin',
                password: 'changeme'
            });`

Thank you!

**Comment by tdhellmann** [comment]
Hey @saibimajdi - we can't support this through the front end. We'd recommend setting up a web app that does authentication via a proxy on the back end.

**Comment by vyazadji** [comment]
Why it possible to do in node.js https://github.com/splunk/splunk-javascript-logging but not in browser ?

**Comment by shakeelmohamed** [comment]
@vyazadji The JS logging library that you've linked to only supports Splunk HEC which is a specific port and set of endpoints only for ingesting data.

This JS SDK faces the same limitations of the underlying Splunk REST APIs and this is unlikely to change anytime soon.
