### ISSUE TITLE
Support login using bearer token instead of login/password

### ISSUE THREAD

**Issue by vyazadji** [splunk/splunk-sdk-javascript#72]
There are login examples only with login/password. It's not secure to use it in browser. Can I use token for login like you do it in https://github.com/splunk/splunk-javascript-logging ?

**Comment by shakeelmohamed** [comment]
Hi @vyazadji, the answer is no. This is a limitation of the underlying REST API for Splunk Enterprise. See #71

**Comment by steventhanna** [comment]
For anyone who stumbles across this... i was able to get token based authentication for Splunk Deployments 7.3+ by doing the following:

```js
let auth = {
    host: {example},
    scheme: {example},
    port: {example},
    sessionKey: {YOUR TOKEN HERE},
    authorization: "Bearer"
}
// Your desired HTTP Abstraction, using JQueryHttp() as an example
let http = new splunkjs.JQueryHttp();
let service = new splunkjs.Service(http, auth);
```

**Comment by pgoldweic** [comment]
@steventhanna thanks for your example! I was just struggling to figure out how to do this myself with the javascript sdk (and posted in Splunk Answers about it). However, when I use it I still get a 400 response. The only difference in my code is as follows:
    
     var http = new splunkjs.ProxyHttp("/mypathtoaserverproxy"); // this is pointing to a proxy server within my same domain
     (the rest is essentially the same)

Any thoughts on what could be going on? 
It's unfortunate that Splunk hasn't yet updated their docs as promised.

**Comment by vmalaviya-splunk** [comment]
Greetings @vyazadji,
Current version of Splunk supports authentication using sessionKey as well as token.
Examples and docs will be updated in next release.
