### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jirwin** [splunk/splunk-sdk-javascript#73]
I've noticed that https://github.com/splunk/splunk-sdk-javascript/pull/69 was a major overhaul and fixes some security vulnerabilities. Can we get a release with this patch included? Thanks.

**Comment by shakeelmohamed** [comment]
Hi @jirwin, we are waiting on the release to fix some test issues against Splunk 7.2. We'd love some help if you're interested. You can see our progress so far in #70

**Comment by amelcharai** [comment]
Hi @shakeelmohamed, did you make some progress on this issue?

**Comment by shakeelmohamed** [comment]
Hi @amelcharai, appreciate your follow up. Unfortunately we haven't gotten a release out yet.

If you folks need to use what's in progress so far, you can pull from the `develop` branch. Let me know if you need guidance around how to do that with npm

**Comment by shakeelmohamed** [comment]
Hey folks, wanted to give you all an update. I'll get a release out by next week, just tying off some loose ends, thanks for your patience.

**Comment by shakeelmohamed** [comment]
Thanks for you patience @jirwin @amelcharai. I've just released v1.9.0 on npm, give it a try!

**Comment by amelcharai** [comment]
Perfect, thank you!
