### ISSUE TITLE
Not sure if this regex does what you want

### ISSUE THREAD

**Issue by LouisMichael** [splunk/splunk-sdk-javascript#74]
I was looking through some project regex and found this one [here](https://github.com/splunk/splunk-sdk-javascript/blob/fc96f0a0491feea6e4878155084ab1f4d53074d6/contrib/dox/markdown.js#L275). Testing it I found that it accepts `[.]:<a>"."Z` note the literal Z at the end.
This is because javascript does not support \Z as an anchor the way some regex languages do and instead will match literal Z.

**Comment by shakeelmohamed** [comment]
@LouisMichael this code is part of the `dox` module which is a 3rd party dependency. If there's a newer version that addresses the fix, please submit a pull request with the appropriate change.
