### ISSUE TITLE
statusCode 600 EAI_AGAIN

### ISSUE THREAD

**Issue by lmeyerov** [splunk/splunk-sdk-javascript#83]
We're getting a 600 error EAI_AGAIN on splunk sdk 1.8.x hitting a splunk 7.2 server. Doing curl from the same box works. This is somewhere around service create & login.

Original setup was a bit crazy (invalid certs so were suppressing that, similar to curl -k), and next we're updating sdk to 1.9.x, but we're running out of ideas.

Thoughts? Any minimal tests that it'd help to try & report?

**Comment by lmeyerov** [comment]
Looking a bit closer: this is on `service.login()`

**Comment by shakeelmohamed** [comment]
Hi @lmeyerov thanks for the bug report. Can you try v1.9.0, we haven't run into this issue yet.
I should mention that we likely won't get a chance to address this until after .Conf - if you're coming shoot me an email and we can find some time to meet.

**Comment by lmeyerov** [comment]
Thanks @shakeelmohamed . We can mark this as closed: It looks like the issue was DNS. In particular, we were running `splunk` -> `docker` -> `splunk js sdk`, and needed to change docker from `node:alpine` to `node:stretch-slim` due to the mysteries of DNS and enterprise deployments. I'm not sure what that says for splunk js sdk prereqs / suggested envs.
