### ISSUE TITLE
Undefined error on invalid Splunk URL

### ISSUE THREAD

**Issue by MisterMX** [splunk/splunk-sdk-javascript#88]
### Expected Behaviour
If a wrong URL is passed to Splunk it should fail with a respective error message.

### Current Behaviour

If a wrong Splunk URL is passed to the `new splunk.Service(config)` nodejs crashes with the following error message:

```
TypeError: Cannot read property 'wasAborted' of undefined
```

This is probably because of the following code in `platform/node/node_http.js`:
```
var req = request(request_options, function (error, res, data) {
    // If we already aborted this request, then do nothing
    if (req.wasAborted) {
        return;
    }
    /* ... */
});
```

If an invalid URL is passed to `request` the callback is invoked immediately before `var req` is set resulting in an error at `if (req.wasAborted) {`

### Possible solution 

Check if `req` is undefined before accessing its properties.

### Steps to Reproduce

Create a new NodeJS Splunk Client with an invalid URL, i.e. `host: '$%&sss'`.

**Comment by shakeelmohamed** [comment]
@MisterMX thanks for the bug report, we're open to a PR if you're interested in adding that `undefined` check

**Comment by MisterMX** [comment]
Added a PR for this issue.

I want to note that the request package is deprecated since recently (https://github.com/request/request#deprecated). You might think about switching to an alternative library in the future.

Best

**Comment by vmalaviya-splunk** [comment]
@MisterMX Thanks for reaching out to us.
Here are our findings regarding the issue that you raised.

1. When we pass an invalid host url to service instance we get following error:
```
{
  response: { headers: {}, statusCode: 600 },
  status: 600,
  data: undefined,
  error: Error: connect ECONNREFUSED 127.0.0.1:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 443
  }
}
```

  It’s not throwing any exceptions and working as expected.
  We suggest you to try the latest SDK and Splunk 8.0 or later.

2. We have added support for needle http library as a replacement of deprecated request library.
