### ISSUE TITLE
use semantic versioning

### ISSUE THREAD

**Issue by PixnBits** [splunk/splunk-sdk-javascript#89]
[`v1.9.0`](https://github.com/splunk/splunk-sdk-javascript/blob/1.9.0/CHANGELOG.md#v190) had a breaking change (as did v1.5.0, v1.3.0, v1.2.0, and v1.1.0), so should have bumped a major version instead of the minor. Part of publishing an npm package is adhering to semver (https://docs.npmjs.com/about-semantic-versioning & https://semver.org/). Please use semantic versioning. Cheers!

**Comment by shakeelmohamed** [comment]
@PixnBits thank you for the issue. At this point since we haven't followed semver for this repo, I don't think we will until we have the bandwidth to invest significant effort into this SDK again. I understand your frustration, we are doing the best we can.

**Comment by ncanumalla-splunk** [comment]
@PixnBits Thank you for the feedback. We will plan to include this in the next major release of the SDK. Closing for now but please reopen if this is an issue.
